// Fictional people, reserved example.com addresses and demonstration phone numbers.
const PEOPLE = [
  ['Alex Morgan', 'United States', 'Northstar Studio'],
  ['Maria Stone', 'United Kingdom', 'Frame & Form'],
  ['James Kim', 'South Korea', 'Orbit Labs'],
  ['Sarah Wilson', 'Canada', 'Maple Design'],
  ['Daniel Garcia', 'Spain', 'Sol Creative'],
  ['Emma Taylor', 'Australia', 'Coast Studio'],
  ['Ali Karimov', 'Uzbekistan', 'Atlas Digital'],
  ['Sofia Rossi', 'Italy', 'Forma Collective'],
  ['Liam Brown', 'United States', 'Northstar Studio'],
  ['Nina Patel', 'United Kingdom', 'Bright Works'],
  ['Leo Martin', 'Canada', 'Maple Design'],
  ['Olivia Clark', 'Australia', 'Coast Studio'],
  ['Aziza Saidova', 'Uzbekistan', 'Atlas Digital'],
  ['Lucas Silva', 'Brazil', 'Verde Studio'],
  ['Chloe Dubois', 'France', 'Atelier Bleu'],
  ['Noah Fischer', 'Germany', 'Kern Design'],
  ['Mia Chen', 'Singapore', 'Daylight Labs'],
  ['Ethan Park', 'South Korea', 'Orbit Labs'],
  ['Isabella Costa', 'Brazil', 'Verde Studio'],
  ['Oliver Reed', 'United Kingdom', 'Bright Works'],
  ['Laylo Rustamova', 'Uzbekistan', 'Atlas Digital'],
  ['Amelia Scott', 'United States', 'Fieldwork'],
  ['Henry Adams', 'Canada', 'Maple Design'],
  ['Yuki Tanaka', 'Japan', 'Kumo Studio'],
  ['Luca Bianchi', 'Italy', 'Forma Collective'],
  ['Zoe Laurent', 'France', 'Atelier Bleu'],
  ['Felix Weber', 'Germany', 'Kern Design'],
  ['Grace Lee', 'Singapore', 'Daylight Labs'],
  ['Mateo Lopez', 'Spain', 'Sol Creative'],
  ['Ava Johnson', 'Australia', 'Coast Studio'],
  ['Jasur Akmalov', 'Uzbekistan', 'Atlas Digital'],
  ['Harper Evans', 'United States', 'Fieldwork'],
  ['Aria Moore', 'Canada', 'Maple Design'],
  ['Ren Sato', 'Japan', 'Kumo Studio'],
  ['Alice Moreau', 'France', 'Atelier Bleu'],
  ['Theo Schmidt', 'Germany', 'Kern Design'],
  ['Elena Romano', 'Italy', 'Forma Collective'],
  ['Ben Wright', 'United Kingdom', 'Frame & Form'],
  ['Camila Santos', 'Brazil', 'Verde Studio'],
  ['Min Seo', 'South Korea', 'Orbit Labs'],
];
export function createSeedCustomers() {
  return PEOPLE.map(([full_name, country, company], index) => ({
    id: 'demo-' + String(index + 1).padStart(2, '0'), full_name, country, company,
    email: full_name.toLowerCase().replaceAll(' ', '.') + '@example.com',
    phone_number: '+1 202 555 ' + String(100 + index).padStart(4, '0'),
    isActive: index % 4 !== 2,
    createdAt: new Date(Date.UTC(2026, 0, 5 + index * 3, 12)).toISOString(),
    updatedAt: null,
  }));
}
